server:
  port: 8085

spring:
  config:
    activate:
      on-profile: offline
    import: optional:file:./config-fallback/
  datasource:
    # Apuntamos a la base de datos PostgreSQL del entorno offline
    url: jdbc:postgresql://postgres-db-offline:5432/ecopila_db_offline
    driver-class-name: org.postgresql.Driver
    username: admin
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      enabled: false
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
eureka:
  client:
    enabled: false

app:
  offline-mode: true