server:
  port: 8085

spring:
  config:
    activate:
      on-profile: offline
    import: optional:file:./config-fallback/
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db-offline:5432/ecopila_db_offline}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379
eureka:
  client:
    enabled: false

app:
  offline-mode: true