server:
  port: 8086

spring:
  application:
    name: auth-service
  datasource:
    # Apuntamos a la base de datos PostgreSQL del entorno offline
    url: jdbc:postgresql://postgres-db-offline:5432/ecopila_db_offline
    driver-class-name: org.postgresql.Driver
    username: admin
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    authentication:
      jwt:
        base64-secret: "hRFxCC9ibkLnqP9Js9FiWRbCme1dbLPLIRzQVPKmhK/LscULomJ/flJJpUaZ+M9fa+hT0X4gpeileNbQJrEBrw=="
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always