# render.yaml
# Definición de la infraestructura para el despliegue en Render

services:
  # 1. Base de Datos PostgreSQL (Servicio Gestionado de Render)
  - type: pserv # PostgreSQL Service
    name: ecopila-postgres-db
    plan: free # Puedes cambiar a 'starter' o 'standard' si necesitas más recursos
    postgresMajorVersion: 14
    # disk: # Opcional: Si necesitas persistencia de datos más allá del ciclo de vida del servicio
    #   name: ecopila-db-disk
    #   sizeGB: 10

  # 2. Servicio de Caché Redis (Servicio Gestionado de Render)
  - type: redis
    name: ecopila-redis
    plan: free # Puedes cambiar a 'starter' o 'standard'
    ipAllowList: # Permite conexiones solo desde los servicios de Render
      - source: 0.0.0.0/0
        description: Allow all internal Render IPs

  # 3. Servicio de Descubrimiento Eureka
  - type: web
    name: eureka-service
    env: JAVA_SPRING_BOOT # Render optimiza el despliegue para apps Spring Boot
    dockerfilePath: ./eureka-service/Dockerfile
    buildFilter:
      paths:
        - eureka-service/**
        - pom.xml
        - .mvn/**
    healthCheckPath: /actuator/health
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: online
    # Puerto interno de Eureka (no es necesario exponerlo públicamente)
    # Render se encarga de la comunicación interna
    ports:
      - 8761

  # 4. API Gateway
  - type: web
    name: gateway
    env: JAVA_SPRING_BOOT
    dockerfilePath: ./gateway/Dockerfile
    buildFilter:
      paths:
        - gateway/**
        - pom.xml
        - .mvn/**
    healthCheckPath: /actuator/health
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: online
      - key: EUREKA_URI # Apunta al servicio Eureka interno de Render
        value: http://eureka-service:8761/eureka
      - key: JWT_SECRET # Se obtiene de los secretos de Render
        sync: false # No sincronizar desde el repo, se gestiona en Render
        fromSecret: jwt_secret_key # Nombre del secreto en Render
      - key: SPRING_DATA_REDIS_HOST # Apunta al servicio Redis interno de Render
        value: ecopila-redis
      - key: SPRING_DATA_REDIS_PORT
        value: 6379
    # Puerto público del Gateway
    ports:
      - 8090

  # 5. Servicio de Autenticación
  - type: web
    name: auth-service
    env: JAVA_SPRING_BOOT
    dockerfilePath: ./auth-service/Dockerfile
    buildFilter:
      paths:
        - auth-service/**
        - pom.xml
        - .mvn/**
    healthCheckPath: /actuator/health
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: online
      - key: JWT_SECRET_KEY # Se obtiene de los secretos de Render
        sync: false
        fromSecret: jwt_secret_key
      # Conexión a la base de datos gestionada de Render
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ecopila-postgres-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ecopila-postgres-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ecopila-postgres-db
          property: password
    ports:
      - 8086

  # 6. Servicio de Producto
  - type: web
    name: producto-service
    env: JAVA_SPRING_BOOT
    dockerfilePath: ./microservicio_producto/Dockerfile
    buildFilter:
      paths:
        - microservicio_producto/**
        - pom.xml
        - .mvn/**
    healthCheckPath: /actuator/health
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: online
      - key: EUREKA_URI
        value: http://eureka-service:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ecopila-postgres-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ecopila-postgres-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ecopila-postgres-db
          property: password
    ports:
      - 8083

  # 7. Servicio de Proveedor
  - type: web
    name: proveedor-service
    env: JAVA_SPRING_BOOT
    dockerfilePath: ./microservicio_proveedor/Dockerfile
    buildFilter:
      paths:
        - microservicio_proveedor/**
        - pom.xml
        - .mvn/**
    healthCheckPath: /actuator/health
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: online
      - key: EUREKA_URI
        value: http://eureka-service:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ecopila-postgres-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ecopila-postgres-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ecopila-postgres-db
          property: password
    ports:
      - 8084

  # 8. Servicio de Tipo de Producto
  - type: web
    name: tipo-producto-service
    env: JAVA_SPRING_BOOT
    dockerfilePath: ./microservicio_tipo_producto/Dockerfile
    buildFilter:
      paths:
        - microservicio_tipo_producto/**
        - pom.xml
        - .mvn/**
    healthCheckPath: /actuator/health
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: online
      - key: EUREKA_URI
        value: http://eureka-service:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ecopila-postgres-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ecopila-postgres-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ecopila-postgres-db
          property: password
    ports:
      - 8085

  # 9. Servicio de Dolar
  - type: web
    name: dolar-service
    env: JAVA_SPRING_BOOT
    dockerfilePath: ./microservicio_dolar/Dockerfile
    buildFilter:
      paths:
        - microservicio_dolar/**
        - pom.xml
        - .mvn/**
    healthCheckPath: /actuator/health
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: online
      - key: EUREKA_URI
        value: http://eureka-service:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ecopila-postgres-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ecopila-postgres-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ecopila-postgres-db
          property: password
    ports:
      - 8082

  # 10. SymmetricDS Master
  - type: web
    name: symmetricds-master
    dockerfilePath: ./symmetricds/master/Dockerfile
    buildFilter:
      paths:
        - symmetricds/master/**
        - symmetricds/insert_config.sql
        - symmetricds/symmetric-ds-3.14.0/**
    healthCheckPath: /sync/master # O el endpoint de salud de SymmetricDS
    plan: free
    envVars:
      # Render inyecta automáticamente PGHOST, PGPORT, PGDATABASE, PGUSER, PGPASSWORD
      # para la base de datos vinculada.
      # RENDER_EXTERNAL_HOSTNAME es el hostname público de este servicio en Render.
      - key: SYMMETRIC_MASTER_HOST # Usado en master.properties para sync.url
        value: ${RENDER_EXTERNAL_HOSTNAME}
    # El comando usa 'sed' para inyectar las variables de entorno en master.properties
    # y luego ejecuta el script de inicialización.
    command: >
      sh -c "
        sed -i 's|db.url=.*|db.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?stringtype=unspecified|' /app/symmetric-ds-3.14.0/engines/master.properties &&
        sed -i 's|db.user=.*|db.user=${PGUSER}|' /app/symmetric-ds-3.14.0/engines/master.properties &&
        sed -i 's|db.password=.*|db.password=${PGPASSWORD}|' /app/symmetric-ds-3.14.0/engines/master.properties &&
        sed -i 's|sync.url=.*|sync.url=http://${RENDER_EXTERNAL_HOSTNAME}:31415/sync|' /app/symmetric-ds-3.14.0/engines/master.properties &&
        chmod +x /app/init-symmetric-master.sh &&
        exec /app/init-symmetric-master.sh
      "
    # Puerto de SymmetricDS para la sincronización con clientes
    ports:
      - 31415
