# render.yaml
# Definición de la infraestructura para el despliegue en Render

services:
  # 1. Base de Datos PostgreSQL
  - type: postgres
    name: ecopila-postgres-db
    plan: free
    postgresMajorVersion: 14

  # 2. Servicio Redis
  - type: redis
    name: ecopila-redis
    plan: free
    ipAllowList: [] # vacío = solo accesible desde servicios de Render

  # 3. Servicio de Eureka
  - type: web
    name: eureka-service
    dockerfilePath: ./eureka-service/Dockerfile
    buildFilter:
      paths:
        - eureka-service/**
        - pom.xml
        - .mvn/**
    healthCheckPath: /actuator/health
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: online

  # 4. API Gateway
  - type: web
    name: gateway
    dockerfilePath: ./gateway/Dockerfile
    buildFilter:
      paths:
        - gateway/**
        - pom.xml
        - .mvn/**
    healthCheckPath: /actuator/health
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: online
      - key: EUREKA_URI
        value: http://eureka-service:8761/eureka
      - key: JWT_SECRET
        fromSecret: jwt_secret_key
      - key: SPRING_DATA_REDIS_HOST
        value: ecopila-redis
      - key: SPRING_DATA_REDIS_PORT
        value: 6379

  # 5. Auth Service
  - type: web
    name: auth-service
    dockerfilePath: ./auth-service/Dockerfile
    buildFilter:
      paths:
        - auth-service/**
        - pom.xml
        - .mvn/**
    healthCheckPath: /actuator/health
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: online
      - key: JWT_SECRET_KEY
        fromSecret: jwt_secret_key
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ecopila-postgres-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ecopila-postgres-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ecopila-postgres-db
          property: password

  # 6. Producto Service
  - type: web
    name: producto-service
    dockerfilePath: ./microservicio_producto/Dockerfile
    buildFilter:
      paths:
        - microservicio_producto/**
        - pom.xml
        - .mvn/**
    healthCheckPath: /actuator/health
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: online
      - key: EUREKA_URI
        value: http://eureka-service:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ecopila-postgres-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ecopila-postgres-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ecopila-postgres-db
          property: password

  # 7. Proveedor Service
  - type: web
    name: proveedor-service
    dockerfilePath: ./microservicio_proveedor/Dockerfile
    buildFilter:
      paths:
        - microservicio_proveedor/**
        - pom.xml
        - .mvn/**
    healthCheckPath: /actuator/health
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: online
      - key: EUREKA_URI
        value: http://eureka-service:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ecopila-postgres-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ecopila-postgres-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ecopila-postgres-db
          property: password

  # 8. Tipo Producto Service
  - type: web
    name: tipo-producto-service
    dockerfilePath: ./microservicio_tipo_producto/Dockerfile
    buildFilter:
      paths:
        - microservicio_tipo_producto/**
        - pom.xml
        - .mvn/**
    healthCheckPath: /actuator/health
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: online
      - key: EUREKA_URI
        value: http://eureka-service:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ecopila-postgres-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ecopila-postgres-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ecopila-postgres-db
          property: password

  # 9. Dolar Service
  - type: web
    name: dolar-service
    dockerfilePath: ./microservicio_dolar/Dockerfile
    buildFilter:
      paths:
        - microservicio_dolar/**
        - pom.xml
        - .mvn/**
    healthCheckPath: /actuator/health
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: online
      - key: EUREKA_URI
        value: http://eureka-service:8761/eureka
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ecopila-postgres-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ecopila-postgres-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ecopila-postgres-db
          property: password

  # 10. SymmetricDS Master
  - type: web
    name: symmetricds-master
    dockerfilePath: ./symmetricds/master/Dockerfile
    buildFilter:
      paths:
        - symmetricds/master/**
        - symmetricds/insert_config.sql
        - symmetricds/symmetric-ds-3.14.0/**
    healthCheckPath: /sync/master
    plan: free
    envVars:
      - key: SYMMETRIC_MASTER_HOST
        value: ${RENDER_EXTERNAL_HOSTNAME}
    command: >
      sh -c "
        sed -i 's|db.url=.*|db.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?stringtype=unspecified|' /app/symmetric-ds-3.14.0/engines/master.properties &&
        sed -i 's|db.user=.*|db.user=${PGUSER}|' /app/symmetric-ds-3.14.0/engines/master.properties &&
        sed -i 's|db.password=.*|db.password=${PGPASSWORD}|' /app/symmetric-ds-3.14.0/engines/master.properties &&
        sed -i 's|sync.url=.*|sync.url=http://${RENDER_EXTERNAL_HOSTNAME}:31415/sync|' /app/symmetric-ds-3.14.0/engines/master.properties &&
        chmod +x /app/init-symmetric-master.sh &&
        exec /app/init-symmetric-master.sh
      "
