server:
  port: 8090

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: false # Deshabilitar descubrimiento dinámico
      routes:
        - id: auth-service-offline
          uri: http://auth-service:8086
          predicates: [ Path=/api/auth/** ]
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: authFallback
                # No definimos fallbackUri, así que devolverá un 503 Service Unavailable, lo cual está bien.

        - id: producto-offline
          uri: http://producto-service:8083
          predicates: [ Path=/api/producto/** ]
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: productoFallback
                fallbackUri: forward:/fallback/producto # Ya tienes un fallback para este

        - id: proveedor-offline
          uri: http://proveedor-service:8084
          predicates: [ Path=/api/proveedor/** ]
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: proveedorFallback

        - id: tipo-producto-offline
          uri: http://tipo-producto-service:8085
          predicates: [ Path=/api/tipo-producto/** ]
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: tipoProductoFallback

        # La ruta del dólar ya está bien configurada con su fallback
        - id: dolar-offline
          uri: http://dolar-service:8082
          predicates: [ Path=/api/dolar/** ]
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: dolarFallback
                fallbackUri: forward:/fallback/dolar

  data:
    redis:
      host: redis # Nombre del servicio Redis en Docker Compose

# Deshabilitar Eureka
eureka:
  client:
    enabled: false

# Propiedad para el secreto del JWT
application:
  security:
    authentication:
      jwt:
        base64-secret: "hRFxCC9ibkLnqP9Js9FiWRbCme1dbLPLIRzQVPKmhK/LscULomJ/flJJpUaZ+M9fa+hT0X4gpeileNbQJrEBrw==" # Tu clave secreta real

logging: # <--- AÑADIR ESTA SECCIÓN
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    org.springframework.cloud.gateway.filter.GatewayFilter: DEBUG
    org.springframework.cloud.gateway.route.RouteLocator: DEBUG
    reactor.netty.http.client: DEBUG