server:
  port: 8761

spring:
  application:
    name: eureka-service
  security:
    basic:
      enabled: false
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    hostname: eureka-service
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.web: DEBUG
    micro.eurekaservice: DEBUG
