spring:
  security:
    basic:
      enabled: false
  mvc:
    contentnegotiation:
      favor-path-extension: false
      favor-parameter: false
      ignore-accept-header: false
      default-content-type: application/json
      media-types:
        json: application/json
  cloud:
    config:
      enabled: false  # Deshabilitar conexión a Config Service
  main:
    allow-circular-references: true  # Habilita referencias circulares
    allow-bean-definition-overriding: true  # Mantén esto si aún es necesario
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  dashboard:
    enabled: true
  server:
    response-cache-update-interval-ms: 30000
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
    registry-sync-retries: 0
    disable-delta: true # Evitar que ignore registros locales
  instance:
    hostname: localhost

logging:
  level:
    com.netflix.eureka: DEBUG    # O TRACE para el máximo detalle
    com.netflix.discovery: DEBUG # O TRACE
    org.springframework.web: DEBUG # Para ver el manejo de peticiones HTTP
    # También puede ser útil para tu clase personalizada:
    micro.example.eurekaservice.config.micro.eurekaservice.eurekaservice.config.PersistentInstanceRegistry: DEBUG