server:
  port: 8084
spring:
  config:
    activate:
      on-profile: online
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/ecopila_db_online
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  # --- CONFIGURACIÓN DE CACHÉ CON REDIS ---
  # (Añadido para que el perfil 'online' se conecte a Redis)
  cache:
    type: redis
  data:
    redis:
      host: redis-online # Nombre del servicio de Redis en docker-compose.online.yml
      port: 6379

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service-online:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
