spring:
  application:
    name: microservicio-proveedor
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: flyway_schema_history_proveedor
management:
  tracing:
    sampling:
      probability: 1.0