server:
  port: 8083
spring:
  config:
    activate:
      on-profile: online
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/ecopila_db_online
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service-online:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true

app:
  storage:
    archive: /data/ventas_online